## 1. Creating Arrays

In [1]:
import numpy as np
import math

In [2]:
a = np.array([1, 2, 3])            # 1D array
b = np.array([[1, 2], [3, 4]])     # 2D array

## 2. Array Indexing & Slicing

In [3]:
a[0]         # First element

1

In [4]:
b[1, 1]      # Element at 2nd row, 2nd column

4

In [5]:
a[1:]        # Slice from index 1 to end

array([2, 3])

## 3. Shape, Reshape, Dimensions

In [6]:
print(a.shape)
print(b.ndim)
c = a.reshape(3,1)
print("reshape:\n",c)

(3,)
2
reshape:
 [[1]
 [2]
 [3]]


## 4. Broadcasting

In [7]:
a = np.array([1, 2, 3])
b = a + 5   

print(b)

[6 7 8]


## 5. Element-wise Operations

In [8]:
x = np.array([1, 2, 3])
y = np.array([4, 5, 6])         

In [9]:
x + y 

array([5, 7, 9])

In [10]:
x * y 

array([ 4, 10, 18])

## 6. Special Arrays

In [11]:
print(np.zeros((2, 3)))  
print("")
print(np.ones((3, 2)))  
print("")
print(np.arange(0, 10, 2))
print("")
print(np.linspace(0, 1, 5))

[[0. 0. 0.]
 [0. 0. 0.]]

[[1. 1.]
 [1. 1.]
 [1. 1.]]

[0 2 4 6 8]

[0.   0.25 0.5  0.75 1.  ]


## 7. Aggregate Functions

In [12]:
# arr = np.array([1, 2, 3, 4])

print(arr.sum())
print("")
print(arr.mean())
print("")
print(arr.std())
print("")
print(arr.max())
print("")
print(arr.min())
print("")

NameError: name 'arr' is not defined

## 8. Useful Utilities

# Advanced NumPy

## 1. Boolean Indexing & Masking

In [ ]:
arr = np.array([1, 2, 3, 4])
arr[arr > 2]    

## 2. Fancy Indexing

In [ ]:
arr = np.array([10, 20, 30, 40])
arr[[0, 2]]      

## 3. Advanced Broadcasting

In [ ]:
a = np.array([[1], [2], [3]])  # Shape (3,1)
b = np.array([10, 20, 30])     # Shape (3,)
a + b                         

## 4. Axis Manipulation

In [ ]:
arr = np.array([[1, 2], [3, 4]])
arr.sum(axis=0)     # [4, 6] → column-wise

In [ ]:
arr.sum(axis=1)     # [3, 7] → row-wise

## 5. Vectorization vs Loops (Speed Boosting)

In [ ]:
#Use NumPy instead of loops for speed:

# Slow way
[math.sqrt(i) for i in range(1000)]

In [ ]:
# Fast NumPy way
np.sqrt(np.arange(1000))

## 6. Broadcasting Rules

## 7. Memory Views vs Copies

In [ ]:
a = np.array([1, 2, 3])
b = a.view()
b[0] = 100       # Also changes a[0]!

In [ ]:
print(b)